name: manifest

on:
  push:
    branches:
    - feature/*
  pull_request:
    branches:
    - main

jobs:
  manifest:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check extension manifest
      run: |
        pip install --user check-jsonschema        
        check-jsonschema --schemafile json-schema/master-manifest.json extensions.json
