name: manifest

on:
  workflow_call:

jobs:
  manifest:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run prospector static analysis
      run: |
        pip install --user check-jsonschema
        curl -o /tmp/extension-manifest.json
        check-jsonschema --schemafile /tmp/extension-manifest.json manifest.json
